### PR TITLE
Replaced deprecated org.springframework.core.LocalVariableTableParameterNameDiscoverer with org.springframework.core.DefaultParameterNameDiscoverer

### PR DESCRIPTION
**Pull request by krupt**

### CODE REVIEW

**Comment by bnasslahsen** [comment]
@krupt,

I have fixed your PR:
LocalVariableTableParameterNameDiscoverer should have been replaced by StandardReflectionParameterNameDiscoverer.

**Comment by krupt** [comment]
But why? StandardReflectionParameterNameDiscoverer can't work for every library. DefaultParameterNameDiscoverer is better, cause it's uses all posible options. First Kotlin, if exists, then StandardReflectionParameterNameDiscoverer for classes that were compiled with Java 8+ with -parameters option and then LocalVariableTableParameterNameDiscoverer for all other classes. That's how it works in Spring Framework

**Comment by bnasslahsen** [comment]
You were breaking tests ...

**Comment by sascha-sphw** [comment]
In which version will this be included?

**Comment by bnasslahsen** [comment]
Read https://github.com/springdoc/springdoc-openapi/releases

**Pull request merged**
