### PR TITLE
Start of @RepositoryRestController documentation generation

### PR DESCRIPTION
**Pull request by speralta**

### CODE REVIEW

**Comment by speralta** [comment]
@bnasslahsen,

I've followed guidelines from CONTRIBUTING.md but there are so many code formatting differences (I'm using eclipse). What can I do ?

**Comment by bnasslahsen** [comment]
@speralta, 

 In fact, there are also the guidelines for Eclipse. 
 But if you are facing troubles about formatting, i can review them, while merging the PR. 
 Just please, make sure  only the really changed lines are reformatted. (It is an option in Eclipse).

I see, there are some failing tests on CI. 
 You can let me know, when the PR is complete and i will do the merge.

**Comment by speralta** [comment]
I've already followed the guidelines for eclipse. I will come back to you when the PR will be ready

**Comment by speralta** [comment]
@bnasslahsen you can start the review

**Comment by bnasslahsen** [comment]
@speralta, 
 
 I will do the merge today.

**Pull request merged**
