### PR TITLE
fix(kotlin): properly generate ByteArray property

### LINKED ISSUE #1688: kotlin ByteArray property incorrect
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

When a model contains a ByteArray field, springdoc does not correctly generate a property definition.

currently this is generated

```json
"properties": {
          "data": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "byte"
            }
          }
        }
```

When is should be 

```json
        "properties": {
          "data": {
            "type": "string",
            "format": "byte"
          }
        }
```

as per https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#data-types

**To Reproduce**
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

I've fixed it here already: https://github.com/springdoc/springdoc-openapi/pull/1687

I'm honestly happy to fix it myself, I just want to document the bug now so no one else gets stuck on it.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by codymikol**
this removes an incorrect wrapper around bytearray
properties.

Fixes #1688

### CODE REVIEW

**Comment by bnasslahsen** [comment]
Thank you @codymikol for your contribution to the project.

**Comment by codymikol** [comment]
No problem :) any idea when the next release is scheduled? Thanks for this project!

**Comment by bnasslahsen** [comment]
@codymikol,

By the end of July!

**Comment by codymikol** [comment]
Awesome! Thanks for the quick response!

**Pull request merged**
