### PR TITLE
Trim indent apply schema description

### PR DESCRIPTION
**Pull request by e-build**
implement #2645

While looking for where to implement the logic to remove the indent of the schema annotation, I wrote it in `AbstractOpenApiResource`. I thought it would be easy to track the implementation according to the `trim-kotlin-indent` setting and add features during future maintenance.

If you think there is a more appropriate class where this implementation should be located, please let me know. I will fix it.

### CODE REVIEW

**Comment by testersen** [comment]
Legendary! I was going to start working on this soon:tm: - time hasn't been on my side lately!

Thanks!

**Comment by testersen** [comment]
Hello my legend @bnasslahsen, do you think it would be possible to merge this soon?

Thanks!

**Comment by bnasslahsen** [comment]
Hi @testersen,

It will be available by the end of month with the next release.

**Comment by testersen** [comment]
@bnasslahsen That's awesome! Thank you!

**Pull request merged**
