### PR TITLE
Add support for externalizing strings in generated openapi schema via…

### PR DESCRIPTION
**Pull request by tkachenkoas**
Originates from https://github.com/springdoc/springdoc-openapi/issues/2401

Can you please hint, what files should be adjusted to publish documentation properly?

### CODE REVIEW

**Comment by tkachenkoas** [comment]
@bnasslahsen please take a look at this PR and let me know if something requires adjustment

**Comment by bnasslahsen** [comment]
@tkachenkoas,

Thank you for your contribution. I believe it's not yet complete.

Do you think you can add the case of OpenAPI groups as well ?

**Comment by tkachenkoas** [comment]
> @tkachenkoas,
> 
> Thank you for your contribution. I believe it's not yet complete.
> 
> Do you think you can add the case of OpenAPI groups as well ?

By "not complete" you mean all fields in the Schema model (like min/max etc.). I didn't plan to add them in the first version, but if you think it makes sense - surely, I'll add it

What case and behavior do you mean by supporting groups? 

E.g. sth like 
```springdoc.specification-strings.{group-name}.paths.{operationId}.description```
should override "general" string
```springdoc.specification-strings.paths.{operationId}.description```

I guess yes, it makes sense when we have identical method names "like getAccount" in UI api and MOBILE api (and in global schema one of them will become ```getAccount_1```)?..

**Comment by bnasslahsen** [comment]
@tkachenkoas,

Sorry for my late response. 
I confirm your properties description, is the exact expected result.

For the method names, more than 99% of cases they are unique per path and it can be considered for the first MVP.
Supporting polymorphism of exposed methods in controller, will bring more complexity and can be considered for another enhancment.

**Comment by tkachenkoas** [comment]
> @tkachenkoas,
> 
> Sorry for my late response. I confirm your properties description, is the exact expected result.
> 
> For the method names, more than 99% of cases they are unique per path and it can be considered for the first MVP. Supporting polymorphism of exposed methods in controller, will bring more complexity and can be considered for another enhancment.

ok, now it's my turn to respond with delay... :)

do I need to modify some other places for this functionality to appear in the documentation?

**Comment by bnasslahsen** [comment]
@tkachenkoas,

It doesn't seem to me that the groups support is implemented.
if it's the case, can you add the the corresponding another test case using ?
```properties
springdoc.specification-strings.{group-name}.paths.{operationId}.description
```

**Comment by tkachenkoas** [comment]
> @tkachenkoas,
> 
> It doesn't seem to me that the groups support is implemented. if it's the case, can you add the the corresponding another test case using ?
> 
> ```ini
> springdoc.specification-strings.{group-name}.paths.{operationId}.description
> ```

ok, I guess I misunderstood one of the previous messages. Adjusted the logic and added a test-case

**Comment by bnasslahsen** [comment]
@tkachenkoas,

Your push was too fast.
i will have to take care of it.

**Comment by bnasslahsen** [comment]
@tkachenkoas,

code merged:
- Removed `springdoc.api-docs.specification-string-properties` property
- Replaced `springdoc.specification-strings` by `springdoc.spec-properties`

**Pull request merged**
