### PR TITLE
@QueryDslPredicate annotation spec support

### PR DESCRIPTION
**Pull request by gibahjoe**
This adds @QueryDslPredicate annotation support i.e Predicate parameters do not just show as empty object but now show as a type

Before
before

After
after

### CODE REVIEW

**Comment by gibahjoe** [comment]
Okay. let me take a look, Will make the changes.

**Comment by gibahjoe** [comment]
Buzz.

Is there an issue with the pr?

**Comment by gibahjoe** [comment]
Hi,I dont know how far you have gone with this review but I want to make some changes and take a different and better approach to achieve this. Is that okay?

**Comment by bnasslahsen** [comment]
Hi @gibahjoe, 

 I have done a first review and merged now with master.
 I will wait for your other changes/better approach and will merge again.

**Pull request closed without merging**
