### PR TITLE
Replace auto-configuration registration

### PR DESCRIPTION
**Pull request by eikemeier**
See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#auto-configuration-registration

### CODE REVIEW

**Comment by jkreileder** [comment]
Fixes #1865

**Comment by mraible** [comment]
It'd be awesome to have a milestone release published with this fix. 🙂

**Comment by TomBeckett** [comment]
Agree, had to revert to previous Spring Boot milestone as we couldn't load swagger 😄

**Comment by bnasslahsen** [comment]
Thank you @eikemeier for your contribution to the project!

**Comment by TomBeckett** [comment]
@bnasslahsen do you know when the next  2.0 milestone is due to be released? 😅

**Comment by bnasslahsen** [comment]
@TomBeckett,

If all good, by the end of this week.

**Comment by forax** [comment]
@bnasslahsen a friendly ping

**Comment by bnasslahsen** [comment]
@forax, Merci pour rappel!

The version 2.0.0-M6 is now released.
The auto-configuration registration errors, should be fixed.

For now, i have left the 2.x branch with the spring-boot-3.0.0-M4. 
I believe the spring-boot-3.0.0-M5 support, still need more time to be fully validated.

**Comment by forax** [comment]
The auto-configuration registration errors are fixed for me, my presentation for devoxx.be now works !
Thanks a lot Badr.

**Comment by bnasslahsen** [comment]
Good luck for your devoxx @forax presentation 🤞 
It's all time a pleasure to see you evangelizing/sharing the up-coming enhancements in Java language!

**Comment by mraible** [comment]
> The version 2.0.0-M6 is now released.

How do I use this release? It doesn't seem to be in Maven central.

**Comment by eikemeier** [comment]
> > The version 2.0.0-M6 is now released.
> 
> How do I use this release? It doesn't seem to be in Maven central.

It is, use the [new module names](https://springdoc.org/v2/#modules), for example [springdoc-openapi-starter-webmvc-api](https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-api).

**Pull request merged**
