### PR TITLE
Use oneOf schema for polymorphic types

### PR DESCRIPTION
**Pull request by zarebski-m**
https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

### CODE REVIEW

**Comment by bnasslahsen** [comment]
Thank you @zarebski-m for this great contribution.

**Comment by zarebski-m** [comment]
@bnasslahsen Any idea when can we expect 1.3.10 release? :)

**Comment by bnasslahsen** [comment]
Hi @zarebski-m, 

The next release will come soon. Hopefully by the end of this week (29/05 at the latest) We just need to finish a major enhancement related to the spring-data-rest, and then we launch the release.

**Comment by bnasslahsen** [comment]
@zarebski-m, 

 The version v1.4.0 is now released. 
 It integrates you PR as well.

**Pull request merged**
