### PR TITLE
feat: springfox compatible

### PR DESCRIPTION
**Pull request by NaccOll**
change code access level and improve springfox compatible by config in default behavior.

[relation issue](https://github.com/springdoc/springdoc-openapi/issues/1743)

### CODE REVIEW

**Comment by NaccOll** [comment]
@bespaltovyj 
I  change access level and imrpove springfox compatible in this pr. But will this be bad, because I don't know the design of this project so well that the configuration I submit does not conform to the specification. I'm wondering if I should just keep the part that modifies the access level of the code so it can be merged faster.

**Comment by bespaltovyj** [comment]
@NaccOll sorry, but I am not involved in this project so deep

**Comment by NaccOll** [comment]
@bespaltovyj Sorry, I typed the wrong username due to autocompletion

**Comment by NaccOll** [comment]
@bnasslahsen 
I change access level and imrpove springfox compatible in this pr. But will this be bad, because I don't know the design of this project so well that the configuration I submit does not conform to the specification. I'm wondering if I should just keep the part that modifies the access level of the code so it can be merged faster.

**Comment by bnasslahsen** [comment]
@NaccOll, 

No problem for changing the access level if there a right justification.
Could you please add the related tests to your PR so we can understand why these changes are necessary ?

**Comment by NaccOll** [comment]
@bnasslahsen 
I think we need to discuss the issue before adding test cases.  As I said in the issue, springdoc's compatibility with springfox is not as good as the documentation says.  More importantly, springdoc does not provide an out-of-the-box behavior consistent with spring mvc. For example, now springdoc treats query parameter objects as json or does not set parameters to form data when specifying api to accept form data.  These default behaviors will cause developers to spend more time writing swagger annotations by themselves.  In this pr, I did two things, one was to modify the access level of the code, and the other was to configure the three problems I said in the issue.  When writing test cases for code access level, do I need to roll back the solution to the problem mentioned in the issue?  It's embarrassing that modifying the code access level is to fix the default behavior bug.  However, I also solved the latter in pr.

**Comment by bnasslahsen** [comment]
@NaccOll,

I have taken in consideration your proposal in this commit https://github.com/springdoc/springdoc-openapi/commit/fb4247868a17502e9c8e29140fe8c0b4efd41364
I didn't add the visibility change of methods and the properties as people can manage achieving it without these.

Thank again for your efforts to make the project adoption easier.

Do not hesistate, to propose additionnal to complete my actual commit. Just make sure the PRs do not mix a lot of changes.

**Pull request closed without merging**
