### PR TITLE
Process @Parameters method parameters as Spring MergedAnnotations

### PR DESCRIPTION
**Pull request by jryan128**
I noticed you used merged annotations while reading method annotations but not method parameters.
This allows the creation of Spring Merged annotations to avoid repeating ourselves:

```java
@Target({PARAMETER, ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Parameter(name = "accountId")
public @interface AccountId {
    @AliasFor(annotation = Parameter.class, value = "example")
    String example() default "123456";
}

...

@GetMapping(value = "/example", produces = MediaType.APPLICATION_JSON_VALUE)
@Operation(description = "example")
public Mono<Void> example(@PathVariable @AccountId String accountId) ...
```

I'll add tests if the maintainers think it's a good idea. Thanks!

### CODE REVIEW

**Comment by jryan128** [comment]
Nevermind I see that the functionality is actually supported already!

**Comment by jryan128** [comment]
Sure thing!

**Comment by jryan128** [comment]
After falling back to `AnnotatedElementUtils`, the Spring Boot 1 demo works fine.

**Comment by bnasslahsen** [comment]
Hi @jryan128, 

 It looks great. Can you just, some tests.
 Once its ready, i will do the merge.

**Comment by jryan128** [comment]
Ready for review.

**Comment by bnasslahsen** [comment]
Great contribution @jryan128 👍 

Thank you for this nice enhancement. 
Its now merged with master.

**Pull request merged**
