### PR TITLE
fix default-flat-param-object doesn't work when using http body

### PR DESCRIPTION
**Pull request by NaccOll**
Related issue：
1. https://github.com/springdoc/springdoc-openapi/issues/2282
2. https://github.com/springdoc/springdoc-openapi/issues/2181

Related pr:
1. https://github.com/springdoc/springdoc-openapi/pull/2183

error behavior:
image

```java
@PreAuthorize("hasPermission(0L,'GLOBAL','cms/column:add')")
@Operation(summary = "创建栏目")
@PostMapping
public CmsColumnDto create(@RequestBody CmsColumnCreateCommand command) {
     ...
}
```
`command` is a json object but converted to multiple query param.

### CODE REVIEW

**Comment by bnasslahsen** [comment]
@NaccOll,

You should provide the complete code of your `HelloController`.
`CmsColumnCreateCommand` declaration is missing.

**Comment by NaccOll** [comment]
@bnasslahsen 
Hold on, I'll provide a repository. But this is unnecessary, because the core of the problem is that the associated pr that Spring recognizes as a JSON object is incorrectly converted into a query object. This resulted in an error in the generated API docs

**Comment by NaccOll** [comment]
@bnasslahsen 
image
This screenshot comes from this [repository](https://github.com/NaccOll/springdoc-default-flat-param-test)

The same object is used for the GET method and the POST method of the same path, where the POST method notifies Spring that it should parse it from the HTTP request body by adding the RequestBody annotation to the parameter. But unfortunately, it was flattened into multiple query parameters, the reason is that when default-flat-param-object is true, it caused problems due to pr ignoring all annotations.

I'm actually confused, I'm the original developer of this feature (https://github.com/springdoc/springdoc-openapi/pull/1805/files), someone misused the feature and modified it, I'm correcting this mistake.

It is hoped that this error will be corrected relatively quickly. I also found another error because of default-support-form-data. When I realized the conversion between Scheme and Paramter, the array was set to null, which caused a null exception when I used this attribute later, but I checked the issue has been now fixed. I hope this pr can be released 2.1.1 after being merged, and fix these two problems of 2.1.0.

**Comment by xiaoymin** [comment]
2.1.1 When will it be released？

**Comment by kylerjensen** [comment]
@bnasslahsen Is there any chance this fix could be back-ported and released as a patch for v1? We're stuck on v1 while we work on our project's Spring Boot 3 upgrade and this issue is blocking us from being able to move forward.

**Comment by bnasslahsen** [comment]
Hi @kylerjensen,

It's already backported in the supported version. 
springdoc-openapi v1.7.0 is the latest Open Source release supporting Spring Boot 2.x and 1.x.
An extended support for [springdoc-openapi v1](https://springdoc.org/v1) project is now available for organizations that need support beyond 2023.
For more details, feel free to reach out: [sales@springdoc.org](mailto:sales@springdoc.org)

**Comment by kylerjensen** [comment]
> It's already backported in the supported version.
> springdoc-openapi v1.7.0 is the latest Open Source release supporting Spring Boot 2.x and 1.x.

Hi @bnasslahsen, thanks for your quick response. I am using v1.7.0 and I am still experiencing this issue. I'm using `springdoc.default-flat-param-object=true` and all my `@RequestBody`-annotated method parameters are being flattened converted to query params. I'm  on Spring Boot v2.3.0.RELEASE for the time being. Do you have any other suggestions? Because of the size of the project, going around and adding `@ParameterObject` is a non-starter.

**Comment by bnasslahsen** [comment]
@kylerjensen,

As stated Earlier, if you need support for this version you should reach out to [sales@springdoc.org](mailto:sales@springdoc.org).

**Comment by kylerjensen** [comment]
Okay, as far as I can tell this fix is definitely _not_ present in v1.7.0. Luckily, there is a [fork](https://github.com/eshizhan/springdoc-openapi/commit/e986414ba532418a902298b028dfe123a9693522) with this fix backported. For anyone coming here looking for a fix for v1, I was able to make it work in my Gradle project through [JitPack](https://jitpack.io/#eshizhan/springdoc-openapi):

```gradle
repositories {
  mavenCentral()
  maven { url 'https://jitpack.io' }
}

dependencies {
  implementation 'com.github.eshizhan.springdoc-openapi:springdoc-openapi-ui:e986414ba5'
  implementation 'com.github.eshizhan.springdoc-openapi:springdoc-openapi-webmvc-core:e986414ba5'
  // ...
}
```

**Pull request merged**
